jobs:
  build_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4         # Call for your Repo files
      - uses: actions/setup-php@v2        # Call for PHP environment
        with:
          php-version: '8.2'
      - name: Build Toolset
        run: |
          sudo apt-get install jq -y      # Call for JSON processor
          chmod +x ./sitemap.sh           # Call for your shell script
          ./sitemap.sh
